version: "3.8"

services:
  airflow:
    image: apache/airflow:3.0.1-python3.11
    container_name: airflow_digest
    restart: always
    env_file:
      - ./.env
    build:
      context: ./airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/utils:/opt/airflow/utils
      - ./airflow/templates:/opt/airflow/templates
    ports:
      - "8080:8080"
    command: airflow standalone
